### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by Alexwijn** [hypzeh/smallify#1]
I'm not sure if there was an update of Spotify but the application has stopped working. And by not working I mean he is unable to retrieve any information from Spotify.

All I get are messages like: "Wherefore are thou Spotify?". Any suggestions?

**Comment by raspberryconverse** [comment]
Same here.  And there is nothing that actually works as well as Smallify, so I'm annoyed.

**Comment by eltoncezar** [comment]
Unfortunately, Spotify changed the way they handle stuff, and now all applications using SpotifyAPI-NET stopped working. You can see more here: https://github.com/JohnnyCrazy/SpotifyAPI-NET/issues/254

**Comment by hypzeh** [comment]
The Spotify changes are unfortunate...
However, I have just released a beta version after a complete rework, with actual authentication. It isn't great as the access token need to be refreshed every hour but it is a new start. 😄
